### ISSUE TITLE
Change 'borough' column name to something more generic and appropriate.

### ISSUE THREAD

**Issue by PublicHealthDataGeek** [PublicHealthDataGeek/GazetteR#2]
For example, 3723277 returns a 'borough' of Guildford which appears to be the location of the Highways England office.  Borough was originally used because we were examining in London whose administrative structures are known as Boroughs rather than local authorities but clearly this column name should reflect the wider content - ? local_authority ? organisation.  It will depend on what the data is.

**Comment by PublicHealthDataGeek** [comment]
also change the 'content' column name in `get_gazette_feed` output to something that reflects what it contains eg web_result_content.  Need to differentiate this between the column 'content_pasted' in from the `get_content` output

**Comment by PublicHealthDataGeek** [comment]
Sorted.

**Comment by Robinlovelace** [comment]
Great work!
